### ISSUE TITLE
Intensity 0

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/MSFragger#105]
Hello,

Thank you so much for all of your previous assistance, I have made some good progress with the software and look forward to investigating it further going forward.

I have many peptides identified that show an intensity of 0, of course those that do show intensities have values of 10^6-10^10. Currently I am not considering those with intensities of 0. 

Is the 0 intensity an artifact of perhaps smoothing or insufficient points across the peak to calculate? Is it proper to exclude these peptides from downstream analysis?

Thank you so much!

**Comment by fcyu** [comment]
Thanks for your interest in our tools. We have some minimum requirements in quantifying a peptide, such as having at least three MS1 scans. If those requirements were not met, a peptide would not have any intensity (we use 0 for it). There can be many reasons of having 0 intensity peptides, but it does not mean that such peptides are not exist in your sample because they have been identified and passed the FDR threshold. So, those peptides should be treated according to the type of your downstream analysis

Best,

Fengchao

**Comment by mcundell** [comment]
How do you get intensity information for the peptide IDs? I do not currently see these in my outputs.  Perhaps one has to run IonQuant or something?

**Comment by fcyu** [comment]
Yes, users need to run IonQuant or Philosopher's freequant. You can load the "LFQ" workflow in FragPipe to get the default settings.

Best,

Fengchao

**Comment by mcundell** [comment]
Thanks for the information. I will give that a try!

**Comment by anesvi** [comment]
Use IonQuant
Just check Ionquant box. If you do quant across multiple samples, you will also need to annotate
runs into experiments to generate multi-experiment report
