### ISSUE TITLE
MSFragger results

### ISSUE THREAD

**Issue by Helleopensearchproteomics** [Nesvilab/MSFragger#132]
Hello! 

I am working on a master thesis project, using MSFragger. I cannot find any result files which include the localisation of the modifications on the protein's amino acid sequence, Where or how can I find this? Do you recommend some special setting? I have used and want to use open search. Also, I can't see the localisation score, or with which certainty it predicts a certain modification. 

I have read through this: https://github.com/Nesvilab/MSFragger/wiki/Interpreting-MSFragger-Output?fbclid=IwAR0ZBjbyH1uFjDXswDwgifUIoadyHdI_-U9_CkaBRKbzIYnOduJcR1UzrqM 
,where it says I should be able to find the modification locations/position on the tsv file at modification_info. But I can't see that either. 

Thank you for your time, 
Best regards

**Comment by fcyu** [comment]
Unfortunately, the protein.tsv and combined_protein.tsv don't have localization of the modification. This is more like a question to [Philosopher](https://github.com/Nesvilab/philosopher).

You should be able to see the `<run name>.tsv` if you are using the default open search.

Best,

Fengchao

**Comment by MNTsnowman** [comment]
Maybe this is not the place for me to add stuff. But I'm kinda wondering the same thing, i have benn looking for glycosylations (=-linked) in some data. There are seom commonly know once that i have found in this file via X!Tandem, now i want to explore if ther are other glycosylations which is what i want to use MSFragger for. I use Fragpipev14 with DB splitting. I have found this guide (https://msfragger.nesvilab.org/tutorial_glyco-fragger.html), modified it slightly to include the "commonly" known glycos and gut it to run without any errors. It says in the bottom that there will be a tsv file with te localization information. i suspect that it is the <run_name>.tsv file it refferes to (?). Even so, it is not really clear to me how this is usefull in locating/discovering glycosylations. Are there more information on the topic somewhere, or could you give an example or two?

**Comment by anesvi** [comment]
Dear MNTsnowman,

At the moment, MSFragger-Glyco basically identifies peptide + Mass shift. So the users need to interpret the data themselves by mapping those mass shifts to glycan structures.
However, this is a priority area for us to add improved mass shift annotation specifically for Glyco searches in the future. We are working on it.

Best,
Alexey

**Comment by MNTsnowman** [comment]
Dear Alexey

 

Sorry for the late reply, and thanks for the reply. 😊

 

I have (finally) been able to open the pepXML files where I can see the some of the mass shifts are localized to some areas that are of interest. However, when browsing through the *.tsv file I can see that there are many more mass shifts that are not found in the pepXML files. Maybe they are filtered out, or? Any ideas?

 

Kind Regards

 

Fra: Alexey Nesvizhskii <notifications@github.com> 
Sendt: 20 February, 2021 15:08
Til: Nesvilab/MSFragger <MSFragger@noreply.github.com>
Cc: MNTsnowman <martinthesbjerg@gmail.com>; Comment <comment@noreply.github.com>
Emne: Re: [Nesvilab/MSFragger] MSFragger results (#132)

 

Dear MNTsnowman, 

At the moment, MSFragger-Glyco basically identifies peptide + Mass shift. So the users need to interpret the data themselves by mapping those mass shifts to glycan structures. 
However, this is a priority area for us to add improved mass shift annotation specifically for Glyco searches in the future. We are working on it. 

Best, 
Alexey

**Comment by MNTsnowman** [comment]
Hello Fengchao

I'm looking at the <run_name>.tsv files usually. However, some of the
others are useful as well... :D When exploring the <rund_name>.tsv file, it
seems to me that there are some slight differences between the entries
therein and in the <rnu_name>.pepXML file. Currently I'm using IDPicker to
handle the pepXML files, could these differences be due to fileteres and
others?

Also, in some of my experiments, IDPicker only shows proteins that are not
part of my sample, thus i suspect these hits are found from the "cRAP" and
decoy/revers filters. But why is it only showing these, is the sample that
badly contaminated, or could the sequences be overlapping and thus causing
confusion? Could i in this case use the <rund_name>.tsv files to "isolate"
the relevant data?


Den tir. 23. feb. 2021 kl. 14.57 skrev Fengchao <notifications@github.com>:

**Comment by fcyu** [comment]
1. Could you show us some examples where <run_name>.tsv and <run_name>.pepXML are different? Those two files are supposed to have the same number of entries.
2. What is the meaning of "IDPicker **only** shows proteins that are not part of my sample"? Does IDPicker show other proteins that are contaminant?

Best,

Fengchao

**Comment by Cajac102** [comment]
Hello,

I'm having difficulties with interpreting the output of open search runs in terms of localisation as well. What I want to extract in the end are mass shifts that could be unambiguously localised at 1% PSM level FDR, and their position in the protein. Preferably using the localisation with the highest score after PTMShepherds rescoring.

I had a look at the protein.tsv file, but as Fengchao already said, it does not include localisation info.
According to the output column descriptions, the "MSFragger Localisation" column in the psm.tsv encodes the localisation information via lower case letters, and "Observed Modifications" shows the mapped UniMod entries (I assume that's one of the PTMShepherd post processing steps, since this column is empty when I don't run PTMShepherd). 
How do I read these? For example:

Assigned Modifications: "7C(57.0214)"
Observed Modifications: 
"Mod1: Unannotated mass-shift -3.8728 (PeakApex: -3.8822); 
Mod1: Unannotated mass-shift -0.9296, Mod2: Unannotated mass-shift -2.9672 (PeakApex: -3.8906); 
Mod1: Unannotated mass-shift -0.9296, Mod2: Unannotated mass-shift -2.9672 (PeakApex: -3.8960)"
MSFragger Localization: "vASTGVCHSDIHHMK"

I would assume that there was a modification that could be unambiguously mapped to the N-Term, since it's the only lower case letter.
1) Are the mass shifts within one ";" combinations that add up to the original mass shift?
2) Why is the second entry in there twice, except for a swapped number in the PeakApex entry?
3) How would a peptidoform show up that contains two modifications at different amino acids? 

The example was from a run with FragPipe 21.1, MSFragger v. 4.0, PTMShepherd v2.0.6, PeptideProphet v5.1.0 on Windows 10.

Best,
Caro
