### ISSUE TITLE
Inaccurate "massdiff" values in pepXML with MSFragger 3.2

### ISSUE THREAD

**Issue by levitsky** [Nesvilab/MSFragger#146]
Hi all,

after testing out MSFragger 3.2 I noticed the following.

As you know, pepXML has several attributes for each PSM: `precursor_neutral_mass`, `calc_neutral_pep_mass` and `massdiff`. The latter is supposed to be the difference between the first two. In older versions of MSFragger, it was the case (accounting for the rounding error to 4 decimal places).
In MSFragger 3.2 I observe discrepancies of ~0.0004 Da between `precursor_neutral_mass - calc_neutral_pep_mass` and `massdiff`, which is strange. When comparing with the old version (2.3) on the same file, I see that both `precursor_neutral_mass` and `calc_neutral_pep_mass` are shifted by ~0.0002 Da, and `massdiff` is shifted by up to 0.0005 compared to the values reported by the old version.
Since `massdiff` is a key quantity in open search analysis, I thought I'd bring this up. I am not attaching any files because I think any file should demonstrate this.

Thank you,

Lev

**Comment by fcyu** [comment]
Hi Lev,

The difference you observed is from the precision difference between double (used by `massdiff`) and float (used by other two). That is also why `precursor_neutral_mass` and `calc_neutral_pep_mass` have up to four decimal points, but `massdiff` has much more. I don't think it matters because the actual mass tolerance/precision is much bigger than 0.0005.

Best,

Fengchao

**Comment by fcyu** [comment]
In case you are not fully convinced. `massdiff` is calculated from `(double) (precursor_neutral_mass - calc_neutral_pep_mass)`. Thus, the difference you observed is from converting float to double, and the small changes in converting it to a String. Maybe we should also use float for `massdiff` to avoid confusion.

Best,

Fengchao
