### ISSUE TITLE
Can MsFragger process samples in separate instances?

### ISSUE THREAD

**Issue by charlin90** [Nesvilab/MSFragger#260]
Hi,
Very nice work. I wonder if MsFragger can run in separate instances, because I have 1000 raw files and multiple independent nodes in HPC. I plan to divide 1000 files into 5 groups and each group has 200 files. In this way, each node can process 200 files and save memory and run time.  If it is possible，how should I combine output from each node?

Charlin
Best wishes

**Comment by fcyu** [comment]
Yes, you can run 200 files on each node. The results files (pepxml and pin) are independent for each raw file.

Since you have many files, I suggest you convert them to mzML first because it would be faster and more robust. Here is the tutorial about the conversion: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by charlin90** [comment]
Thank you for your quick reply. If so, I have another question. These 1000 files are from my single study project. For downstream protein label-free quantification step(use philosopher), if I should combine  mutiple pepxml into one pepxml or directly process each pepxml file in independent manner? Which manner is accurate for downstream differential expression analysis?

Thanks again
