### ISSUE TITLE
MS Fragger DDA+ parameter: What optimal setting for 'Report top N' for DDA+?

### ISSUE THREAD

**Issue by prao123** [Nesvilab/MSFragger#293]
Hello,
I am trying to understand this parameter for DDA+ (Report top N) in the advanced tab of MS Fragger. The default number is 5 for DDA+ and 1 for DDA. Why does increasing this parameter to 5 (for DDA+) from 1 (in DDA) increase the number of protein IDs? 
Looking in to psm.tsv file, it now lists more entries in the spectrum column since rank1 to rank5 spectra are now listed (I understand that). So, is the inclusion of rank2 to rank5 PSMs result in increase in number of protein IDs?
Also, why is the default number of 5 chosen for this parameter for DDA+?

Thank you

**Comment by fcyu** [comment]
DDA+ is different from DDA in the database searching stage. It searches for the peptides within the entire isolation window (following by the refinement processes) to detect the chimeric spectra while DDA only searches for the peptides within a narrow tolerance (e.g., 20 ppm). Since Chimeric spectra exists in most datasets, performing DDA+ results in more IDs.

As to why 5 but not other, it is just a empirical value.

Best,

Fengchao
