### ISSUE TITLE
What is the difference between "precursor_mass_lower/upper" vs "precursor_true_tolerance"?

### ISSUE THREAD

**Issue by gsaxena888** [Nesvilab/MSFragger#40]
I'm a little confused as to the difference between "precursor_mass_lower/upper" vs "precursor_true_tolerance". Could you please clarify? (I read the documentation.) In particular, this is what I'm trying to do:

I'm trying to search a pseudo spectra file that was generated against DIA data. (The pseudo spectra was generated using a tool similar in concept to DIA Umpire.) Because I'm using a pseudo spectra file (and not a "real" DDA spectra), I do *NOT* know the precursor mass precisely; in fact, let's assume that in the common cases, I *only* know that the precursor falls in a 4Da window. In X!Tandem, I was able to *successfully* search this pseudo spectra file by setting the precursor mass of each spectra to *halfway* in between the DIA window (eg if the DIA window was say 600Da to 604Da, I would set the presumed precursor mass to 402Da) and then set the precursor toleration to +- 2Da.

Can something similar be done with MS Fragger, and if so, what should the values be for "precursor_mass_lower/upper" vs "precursor_true_tolerance"? (In X!Tandem, there is only 1 variable that I need to set, the "precursor tolerance", which I set to 2 Da in the above example; but in MSFragger, I'm confused as to which of the above 2 parameters I need to set or if they somehow need to "add up" to 2Da etc.)

All of the questions above are thus far for CLOSED SEARCHES. However, if I then wished to run an open search, would there be any reason why my pseudo spectra (with the very large +- 2Da tolerance for the precursor) not work well in MSFragger due to the super large precursor inprecision? (I ask because I believe it was designed with a more "normal" precursor tolerance in mind, such as 20ppm etc.) Finally, even if OPEN SEARCHES should work for my above described pseudo spectra, would the "add_topN_complementary" be a BAD idea to enable since the precursor tolerance is huge (ie 2 Da)?

**Comment by fcyu** [comment]
The 'precursor_mass_lower/upper' is the actually precursor mass boundaries used in search. For example, `precursor_mass_lower = -20, precursor_mass_upper = 20, precursor_mass_units = 1` would result in 20 ppm precursor mass tolerance, which is a normal closed search. On the other hand, if you set `precursor_mass_lower = -150, precursor_mass_upper = 500, precursor_mass_units = 0`, it would be an open search with [-150, 500] Da precursor mass window.

The `precursor_true_tolerance` is used to break ties in open search and is also used as `precursor_mass_lower/upper` in the first search (if applicable). For example, if you set `precursor_true_tolerance = 20, precursor_true_units = 1`, MSFragger would use `precursor_mass_lower = -20, precursor_mass_upper = 20, precursor_mass_units = 1` in the first search no matter what the actual `precursor_mass_lower/upper` values are. 

In your case, since you don't know the accurate precursor mass, I think set `precursor_mass_lower = -2, precursor_mass_upper = 2, precursor_mass_units = 0, precursor_true_tolerance = 20, precursor_true_units = 1` AND set `calibrate_mass = 0` should be fine. As you can see, such a setting is actually an open search with narrow window.

Best,

Fengchao

**Comment by fcyu** [comment]
Sorry I forgot to answer the `add_topN_complementary` question. I suggest you leave it 0 since you are just performing a closed search with large precursor tolerance.  I guess you are not trying to find open modifications, right?

Best,

Fengchao

**Comment by fcyu** [comment]
Added this question to [FAQ](https://github.com/Nesvilab/MSFragger/wiki/Frequently-Asked-Questions).
