### ISSUE TITLE
Process retured non-zero existing code, stop 

### ISSUE THREAD

**Issue by Liang-aaaaa** [Nesvilab/MSFragger#74]
Dear developers,

We have tried to build peptide library with DDA files acquired by timsTOF on MSFragger, however, an erroe occured as below. 
Process retured non-zero existing code, stop
![image](https://user-images.githubusercontent.com/65036487/81820045-ac673500-9562-11ea-90c5-da2336049e41.png)
We used the default parameters of closed search.
How can we debug this error and complete library building process?

Thanks a lot!
Liang

**Comment by fcyu** [comment]
Hi Liang,

Thanks for your interest in our tools. I see that you are using .d data, which is probability from timsTOF PASEF. Currently, the spectral library building module doesn't support timsTOF data. We will support this in the next release.

Best,

Fengchao

**Comment by nathemie** [comment]
We actually completed database search and generated .pepXML, .pep.xml, ions/peptides/proteins.csv results. Our error message is `Failed to open input file 'xxxx.mzML'.` since we used .d files as the input. Do you think it possible to use external mzML converter (such as OpenSWATH's convertTDFtoMzML.py) or SpectraST to build the library based on those output files? 
We used MSFragger since our Bruker's representatives mentioned that

**Comment by fcyu** [comment]
You are using timsTOF PASEF data, right? In order to build such a library, we need to align ion mobility in additional to retention time. SpectraST cannot do that. So, even you convert your data to mzML, it still won't work. You have to wait for the next release of FragPipe that has another spectral library building module, EasyPQP, to do that.

Best,

Fengchao

**Comment by nathemie** [comment]
Thanks for the fast reply. From our library result built by Spectronaut Pulsar that we would like to compare, `

ReferenceRun | PrecursorCharge | Workflow | IntModifiedPeptide | ModifiedPeptide | StrippedPeptide | iRT | iRTSourceSpecific | BGSInferenceId | IsProteotypic | IntLabeledPeptide | LabeledPeptide | PrecursorMz | ReferenceRunQvalue | ReferenceRunMS1Response | FragmentLossType | FragmentNumber | FragmentType | FragmentCharge | FragmentMz | RelativeIntensity | ExcludeFromAssay | Database | ProteinGroups | UniProtIds | Protein Name | ProteinDescription | Organisms | OrganismId | Genes | Protein Existence | Sequence Version | FASTAName
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


` . It seems there is no IonMobility information. We would like to build a RT-library and not use ion mobility to run a DIA, is the ion mobility alignment compulsory?  To me, the task is to score from the psm results of the corresponding spectrum by scan number via those mzML files or other spectrum files

**Comment by fcyu** [comment]
Solved by email.
