### ISSUE TITLE
Issue converting RAW files with MSFragger on Linux

### ISSUE THREAD

**Issue by mlgill** [Nesvilab/MSFragger#96]
Greetings --

I'm attempting to MSFragger to process some RAW files on Linux and am running into the following issue:

```
Running MSFragger
MSFragger version MSFragger-3.0
Batmass-IO version 1.17.4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 10.0.1, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 64 GB memory
Checking database...
Checking /home/mgill/storage/output/msfragger_PXD004424_closed_semienzymatic/151009_exo3_1.raw...
Failed in checking /home/mgill/storage/output/msfragger_PXD004424_closed_semienzymatic/151009_exo3_1.raw
UNAVAILABLE: Network closed for unknown reason
```

I have mono-devel installed on this machine. Any suggestions for how to debug further or is there other information that I can provide? 

I'd note that I was previously attempting to process this data based on mzML files created from this dataset on Windows with MSConvert on Windows, but ran into an issue with MSFragger where it claimed a tag was missing from one of the spectra and would not process that file. Hence my attempts at switching to RAW.

Thank you!

**Comment by mlgill** [comment]
This is Ubuntu 18.04 with mono-devel as follows:

```
% mono --version
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by fcyu** [comment]
Thanks for your interest in our tools. This error may due to some network/firewall settings in your system, which is very difficult to figure out the solution. On the other hand, could you please share the "broken" mzML with us to take a look? We can give you a link to upload if you need one.

Thanks,

Fengchao

**Comment by mlgill** [comment]
Thanks for your reply @fcyu. 

Could you at least clarify what kind of network call this conversion step is making with RAW files? I'm not clear why that would be needed. 

Network issues are surprising since this is a machine that I fully administer myself which is currently located on my home network, but I understand the difficulty with diagnosing remotely.

For the mzML, it seems to be working now after three different (but identical) tries at conversion. I'll send it if I encounter any additional issues though.

**Comment by fcyu** [comment]
No problem. We use a "server-client" approach to read the RAW with Thermo's library (in C#, as server) and load the data to MSFragger (in Java, as client). I guess some of your operating system's ports are blocked so that MSFragger cannot establish a link.

In terms of converting to mzML, there is a [tutorial](https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md) which may be useful to you.

Best,

Fengchao
